# Generated by Django 3.2.5 on 2021-10-21 06:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RB', '0002_auto_20211018_1116'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resumeexp',
            name='user',
        ),
        migrations.RemoveField(
            model_name='skills',
            name='user',
        ),
        migrations.RemoveField(
            model_name='resumedata',
            name='user',
        ),
        migrations.DeleteModel(
            name='ResumeEdu',
        ),
        migrations.DeleteModel(
            name='ResumeExp',
        ),
        migrations.DeleteModel(
            name='Skills',
        ),
    ]
