# Generated by Django 3.2.5 on 2021-10-22 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RB', '0003_auto_20211021_1131'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resumedata',
            name='id',
        ),
        migrations.AddField(
            model_name='resumedata',
            name='college',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='resumedata',
            name='college_field',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='resumedata',
            name='college_join',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='resumedata',
            name='college_leave',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='resumedata',
            name='college_per',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='resumedata',
            name='obj',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='resumedata',
            name='prof',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='resumedata',
            name='project_name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='resumedata',
            name='school_10',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='resumedata',
            name='school_10_field',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='resumedata',
            name='school_10_join',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='resumedata',
            name='school_10_leave',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='resumedata',
            name='school_10_per',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='resumedata',
            name='school_12',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='resumedata',
            name='school_12_field',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='resumedata',
            name='school_12_join',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='resumedata',
            name='school_12_leave',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='resumedata',
            name='school_12_per',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='resumedata',
            name='skill1',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='resumedata',
            name='skill2',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='resumedata',
            name='skill3',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='resumedata',
            name='tech',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='resumedata',
            name='email',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
    ]
