# Generated by Django 3.2.5 on 2021-10-22 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RB', '0004_auto_20211022_2133'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resumedata',
            old_name='project_name',
            new_name='project',
        ),
        migrations.RenameField(
            model_name='resumedata',
            old_name='obj',
            new_name='project_obj',
        ),
        migrations.RenameField(
            model_name='resumedata',
            old_name='skill1',
            new_name='project_tech',
        ),
        migrations.RenameField(
            model_name='resumedata',
            old_name='skill2',
            new_name='skill_1',
        ),
        migrations.RenameField(
            model_name='resumedata',
            old_name='skill3',
            new_name='skill_2',
        ),
        migrations.RenameField(
            model_name='resumedata',
            old_name='tech',
            new_name='skill_3',
        ),
        migrations.AddField(
            model_name='resumedata',
            name='skill_name_1',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='resumedata',
            name='skill_name_2',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='resumedata',
            name='skill_name_3',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
